#!/bin/sh -e
[ $# -lt 2 ] && { echo "Usage: `basename $0` pid breakpoint ..." 1>&2; exit 1;}
pid=$1
shift

trace_commands=
while [ "$1" ]
do
    trace_commands="$trace_commands
    tracestack $1"
    shift
done
echo $trace_commands
gdb --quiet -nx /proc/$pid/exe $pid <<EOF 2>&1 |
define tracestack
    break \$arg0
    commands
        echo ###\n###\n
        backtrace
        continue
    end
end
$trace_commands
# add tracestack here, if you want to trace more functions
continue
EOF
/bin/sed -n \
        -e '/^(gbd)/p' \
        -e '/^#/p' \
        -e '/^Thread/p'

